### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0dp**
Proposing to reformulate the Getting Started paragraph so there is no doubt about how the inclusion of terser-webpack-plugin works in Webpack v.5 or above.

#416

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Based on discussion in #416 I propose a reformulation of the Getting Started paragraph

### Breaking Changes

No breaking changes

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Please accept CLA

**Comment by 0dp** [comment]
> Please accept CLA

I apologize @alexander-akait Where do I accept the CLA?

**Comment by alexander-akait** [comment]
Oh, CLA is broken... give me time to fix it

**Comment by 0dp** [comment]
> Oh, CLA is broken... give me time to fix it

@alexander-akait it looks like you fixed it and I was able to sign it

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
