### PR TITLE
Update legacy Webpack 3 plugin

### PR DESCRIPTION
**Pull request by etripier**
This PR contains a:

- [x] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

This PR brings the `webpack-3` branch up to date with `master` and further bumps `terser` to `4.1.2` to pick up some performance updates and fixes.

### Breaking Changes

The biggest breaking change is the `terser@4` update from `master`.

### CODE REVIEW

**Comment by etripier** [comment]
@lencioni

**Comment by etripier** [comment]
Interesting - the tests pass locally but fail on CI. I've refreshed the snapshots. What gives?

**Comment by evilebottnawi** [comment]
@etripier thanks for PR, looks like some snapshots not updated

**Comment by evilebottnawi** [comment]
Sorry, webpack@3 fully deprecated

**Comment by evilebottnawi** [comment]
Thanks for PR, we prepare new major release for plugin and officially deprecated webpack@3, better do fork

**Pull request closed without merging**
