### PR TITLE
fix: avoid breakage from terser@4.0.1

### PR DESCRIPTION
**Pull request by jakeNiemiec**
https://github.com/terser-js/terser/issues/380#issuecomment-507067182

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Downstream fix for https://github.com/terser-js/terser/issues/380

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
CLA signed

**Comment by evilebottnawi** [comment]
need update snapshot

**Comment by evilebottnawi** [comment]
We need wait https://github.com/terser-js/terser/pull/382

**Comment by evilebottnawi** [comment]
Done in master, release will be in near future

**Pull request closed without merging**
