### PR TITLE
Support legacy Webpack 3 plugin interface

### PR DESCRIPTION
**Pull request by etripier**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

This PR supports the legacy Webpack 3 plugin interface, allowing this plugin to work for older versions of Webpack.

See https://github.com/webpack-contrib/terser-webpack-plugin/issues/74.

### Breaking Changes

None.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Just clarify, what is boilerplate or place where developers still use `webpack@3`?

**Comment by etripier** [comment]
@evilebottnawi We still use Webpack 3 at Airbnb.

**Comment by etripier** [comment]
@evilebottnawi Should I open this up against a new branch? How should I handle the drop in code coverage? I think I can add a new Git URL for Webpack 3 and then run some basic tests for that particular version in `TerserPlugin.test.js`.

**Comment by evilebottnawi** [comment]
All good, i create `webpack-3` branch. We need:
- Change package name (`terser-webpack-plugin-legacy`)
- Add notice about this in docs

Let's do it in this PR :+1:

**Comment by etripier** [comment]
@evilebottnawi Awesome! Thank you 🙏. What do you think about my changes?

**Comment by evilebottnawi** [comment]
Please fix CI problem, need fix commit message like: `docs: refer to Webpack v3 and terser-webpack-plugin-legacy`

**Comment by etripier** [comment]
@evilebottnawi Thanks for bearing with me - I think we should be good now.

**Comment by evilebottnawi** [comment]
Let's do release

**Pull request merged**
