### PR TITLE
No need to install it if you use webpack v4+

### PR DESCRIPTION
**Pull request by antonk52**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Some people still install and set up this plugin in their webpack explicitly. The proposed line in the readme is supposed to make it easier for the newcomers.

### Breaking Changes

none

### CODE REVIEW

**Review by evilebottnawi — DISMISSED** [review]

**Comment by evilebottnawi** [comment]
There is interesting case, if you use webpack@4 you can install this plugin just using another version

**Comment by evilebottnawi** [comment]
webpack@5 uses the latest version of this plugin

**Comment by antonk52** [comment]
Yep, with webpack v4 it was a common practice to install this plugin explicitly in order to use the latest version. Since currently the latest webpack version is 5 I do not think this needs to be addressed in the readme. Though I am fine with either way. If you can think of a better way to phrase this I am happy to make the idea more transparent for the users.

**Comment by evilebottnawi** [comment]
> If you can think of a better way to phrase this I am happy to make the idea more transparent for the users.

Maybe we add this only for webpack@5? Because currently it can be some misleading for v4

**Review by evilebottnawi — APPROVED** [review]

**Comment by evilebottnawi** [comment]
Thanks

**Pull request merged**
