### PR TITLE
Move the links to the top

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

There is currently some markdown code shown at https://webpack.js.org/plugins/terser-webpack-plugin/

bildschirmfoto 2019-01-18 um 09 26 08

Not 100% sure but this PR might solve it.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> **[evilebottnawi](/evilebottnawi) ** requested changes [ 4 minutes ago](#pullrequestreview-194023514)

Which changes do you want to see here?

**Comment by evilebottnawi** [comment]
@DanielRuf wait answer from @montogeek , just ensure nobody merge this in future (if i was unavailable)

**Comment by montogeek** [comment]
This is fixed in the `rebuild` branch in the webpack.js.org, no need to change it.
image

@DanielRuf Please bear with us, we are about to merge it.

**Comment by evilebottnawi** [comment]
@montogeek please clarify, should we change default template or not?

**Pull request closed without merging**
