### PR TITLE
refactor: show error message from jest-worker

### PR DESCRIPTION
**Pull request by pustovalov**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [x] **test update**  
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

https://github.com/webpack-contrib/terser-webpack-plugin/issues/143#issuecomment-569087575

> looks like bug in jest-worker

https://github.com/facebook/jest/issues/8872#issuecomment-524822081

https://github.com/facebook/jest/blob/master/packages/jest-worker/src/workers/ChildProcessWorker.ts#L93

I think these changes will help to find a problem

### Breaking Changes

Nope

### CODE REVIEW

**Comment by pustovalov** [comment]
I will try

**Comment by pustovalov** [comment]
When writing a test, I found `silent:false` doesn’t work, thanks to this demo: https://github.com/tedconn/worker-jest-ts

```
forkOptions: {
    silent: false,
},

```

```
[~/Downloads/worker-jest-ts-master]$ npm test                                                                                                                                        [ruby-2.6.1]

> worker-jest-ts@1.0.0 test /Users/pavel/Downloads/worker-jest-ts-master
> jest --forceExit

 FAIL  src/__tests__/index.test.js
  invokes the compiler
    ✕ prints the right message (262ms)

  ● invokes the compiler › prints the right message

    Call retries were exceeded

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

Test Suites: 1 failed, 1 total
```

Change `silent: false` to this one
```
if (worker.getStderr()) worker.getStderr().pipe(process.stderr)
```

result:
```
[~/Downloads/worker-jest-ts-master]$ npm test                                                                                                                                        [ruby-2.6.1]

> worker-jest-ts@1.0.0 test /Users/pavel/Downloads/worker-jest-ts-master
> jest --forceExit

/Users/pavel/Downloads/worker-jest-ts-master/src/compiler.ts:1
export async function compile() {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at execMethod (/Users/pavel/Downloads/worker-jest-ts-master/node_modules/jest-worker/build/workers/processChild.js:128:16)
    at process.<anonymous> (/Users/pavel/Downloads/worker-jest-ts-master/node_modules/jest-worker/build/workers/processChild.js:64:7)
    at process.emit (events.js:305:20)
/Users/pavel/Downloads/worker-jest-ts-master/src/compiler.ts:1
export async function compile() {
^^^^^^

  invokes the compiler
    ✕ prints the right message (289ms)

  ● invokes the compiler › prints the right message

    Call retries were exceeded

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
```

but even with `if (worker.getStderr()) worker.getStderr().pipe(process.stderr)` I did not find a way to write a test for this

If I put `process.exit(1)` to the `worker.js`, I see this an error:
```
  console.log src/TaskRunner.js:60
    er Error: Call retries were exceeded
        at ChildProcessWorker.initialize (/Users/pavel/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
        at ChildProcessWorker.onExit (/Users/pavel/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:264:12)
        at ChildProcess.emit (events.js:305:20)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
      type: 'WorkerError'
    }
```

I think we see this error because the process does not have enough memory and it crashes, maybe we can add some debug information to the
https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/TaskRunner.js#L47

something like this
```
const showMemoryUsage = (step = '') => {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`Memory used ${step}: ${Math.round(used * 100) / 100} MB`);
};

showMemoryUsage('on worker error');
```

**Comment by evilebottnawi** [comment]
In theory crash can be not only because of memory, I think we can then avoid the tests, let's just add comments to the code, why are we doing this

**Comment by pustovalov** [comment]
Changed the code from `silent: false` to this implementation:
https://github.com/facebook/jest/blob/master/packages/jest-runner/src/index.ts#L139

**Pull request merged**
