### PR TITLE
feat: update terser to version 4

### PR DESCRIPTION
**Pull request by alan-agius4**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Additional Info
Full terser changelog https://github.com/terser-js/terser/blob/master/CHANGELOG.md#v400

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Ci fail

**Comment by alan-agius4** [comment]
The failure doesn’t seem related https://dev.azure.com/webpack-contrib/terser-webpack-plugin/_build/results?buildId=153

**Comment by evilebottnawi** [comment]
No https://dev.azure.com/webpack-contrib/terser-webpack-plugin/_build/results?buildId=153

**Comment by fabiosantoscode** [comment]
@evilebottnawi The internal AST has changed. If you allow your users to [access the internal AST like this](https://github.com/terser-js/terser/#using-native-terser-ast-with-minify) then it's a major change.

**Comment by evilebottnawi** [comment]
Thanks, we don't allow developers use ast so it is minor release, thanks

**Pull request closed without merging**
